services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  redmine:
    build: .
    restart: always
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    volumes:
      - redmine_data:/usr/src/redmine/files
      - ./configuration.yml:/usr/src/redmine/config/configuration.yml
      - redmine_plugins:/usr/src/redmine/plugins

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080"   # interfaz web
      - "1025:1025"   # puerto SMTP

volumes:
  db_data:
  redmine_data:
  redmine_plugins:
