services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE:   wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - "8001:80"
      restart: always
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: somewordpress

volumes:
  wordpress_data:
  db_data: